# @package eval.tofu.metrics.forget_Q_A_PARA_Prob

defaults:
  - ../../data/datasets@datasets: RTL_QA_forget_para
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: 4

# datasets:
#   TOFU_QA_forget_para:
#     args:
#       hf_args:
#         name: ${eval.tofu.forget_split}_perturbed